// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTJvZDL8nOxXeIzZ7D4eVl8tW7-e_SRKI',
    appId: '1:453047721110:web:297e6dac6ea592f866b6b7',
    messagingSenderId: '453047721110',
    projectId: 'pizza-delivery2',
    authDomain: 'pizza-delivery2.firebaseapp.com',
    storageBucket: 'pizza-delivery2.appspot.com',
    measurementId: 'G-XE0M5KTBCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAybHjMXoxHvrJYMTsv3ir5CDJLx2q0SFw',
    appId: '1:453047721110:android:53bdeebbfc6b289866b6b7',
    messagingSenderId: '453047721110',
    projectId: 'pizza-delivery2',
    storageBucket: 'pizza-delivery2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJld2G_3ZWmFS8qEkfBKsecSTQiwSqOlk',
    appId: '1:453047721110:ios:ed5df876c03ec7d566b6b7',
    messagingSenderId: '453047721110',
    projectId: 'pizza-delivery2',
    storageBucket: 'pizza-delivery2.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJld2G_3ZWmFS8qEkfBKsecSTQiwSqOlk',
    appId: '1:453047721110:ios:f6b7028969499b4e66b6b7',
    messagingSenderId: '453047721110',
    projectId: 'pizza-delivery2',
    storageBucket: 'pizza-delivery2.appspot.com',
    iosBundleId: 'com.example.pizzaApp.RunnerTests',
  );
}
